### ISSUE TITLE
After adding the IOS SDK to the project (IOS 15), it is not possible to build. Multiple errors exist.

### ISSUE THREAD

**Issue by amogga** [IBM/event-notifications-destination-ios-sdk#4]
<img width="257" alt="Screenshot 2022-06-01 at 11 59 24" src="https://user-images.githubusercontent.com/10297206/171368190-13c36cc3-3420-463c-86c0-da9449049924.png">

**Comment by AnanthaKrish** [comment]
@ahmedmogahed 
Hi, 
1. which version of Xcode you are using ?
2. What’s the Xcode target version ? This should be above ios 10.
3. How are you pulling the sdk ?

**Comment by amogga** [comment]
Thanks for your response @AnanthaKrish !

The Xcode version is 13.4, and the deployment target is IOS 15.5. I've used the Swift Package Manager to import the SDK.

**Comment by AnanthaKrish** [comment]
@ahmedmogahed Fixed the issue. Please pull the latest `main` branch to your app.
